name: Check
on:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Check scala file formatting
        run: sbt scalafmtCheck
      - name: Check sbt file formatting
        run: sbt scalafmtSbtCheck
      - name: Run tests
        run: sbt test
